# Generated by Django 2.2.4 on 2020-09-28 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0004_auto_20200923_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.NullBooleanField(verbose_name='Новостройка'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('flat_number',
                 models.IntegerField(verbose_name='Номер квартиры')),
                ('complaint_text',
                 models.TextField(verbose_name='Текст жалобы')),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='profile',
                                   to=settings.AUTH_USER_MODEL,
                                   verbose_name='Кто жаловался')),
            ],
        ),
    ]
