# Generated by Django 2.2.4 on 2020-09-28 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0005_auto_20200928_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='flat_number',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='property.Flat', verbose_name='Номер квартиры'),
        ),
    ]
