# Generated by Django 2.2.4 on 2020-10-06 08:51

from django.db import migrations


def fill_owner_table(apps, schema_editor):
    print('start fill_owner_table function')
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flats = Flat.objects.all()
    for flat in flats:
        owner_name = flat.owner
        owner_phonenumber = flat.owners_phonenumber
        owner_pure_phone = flat.owner_pure_phone

        new_owner, _ = Owner.objects.get_or_create(owner_name=owner_name,
                                                   owner_number=owner_phonenumber,
                                                   owner_pure_phone=owner_pure_phone)

        flat.owners.set([new_owner])


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0011_owner'),
    ]

    operations = [
        migrations.RunPython(fill_owner_table)
    ]
