# Generated by Django 2.2.4 on 2020-10-02 13:15

from django.db import migrations

def fill_owner_info(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_owner'),
    ]

    operations = [
    ]
